---
title: "Conditional Support of Unilateral Action"
author: "Sam Schutt"
date: "April 24, 2019"
font-family: Times New Roman
fontsize: 12pt
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
abstract: How does unilateral action influence public opinion? Through increased reliance on unilateral action to achieve policy goals, Presidents face pressure from judicial branch, legislative branch, and the public. Utilizing this tool comes at a cost to his or her relationship with all three of the groups. With the President's role as "steward of the people" (Teddy Roosevelt), the costs of public opinion on executive order usage are certainly part of the calculation into whether they choose to use it. Using experimental data collected by Reeves and Rogowski (2018), the findings indicate that partisanship plays an important role in determining whether someone supports unilateral action. A new theory is proposed for future discovery, that attempts to define under what conditions presidents should expect public opinion consequences.  

---



```{r setup, include=FALSE}

```
##Introduction


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; During the past two decades, Presidents have sought to overcome the partisan gridlock in Congress, which prevents passage of important policy agenda items, through their use of executive orders. The costs of such usage are often suggested to be a decrease in public opinion or support (Reeves and Rogowski 2018; Krause and Cohen 1997), or less bartering ability with Congress (Kernell 1997; Kiewiet and McCubbins 1985). However, the cost of using executive orders (EOs henceforth) on public opinion plays the largest role in decision-making due to the electoral connection between the President and the nation of individuals.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Unilateral action often to the behest of congressional representatives as a gross overreach of power, or a lack of adherence to the constitution and its norms (Deering and Maltzman 1999). Congress can often be seen making these public outcries to the electorate; often calling for the President to work with Congress or trying to cast doubt on the legitimacy of EOs that they disagree with. However, the modern institution of the President has not been reluctant to continue using EOs to produce favorable outcomes for themselves. To best understand the purpose in Congress making these outcries about Presidential abuse of power, it is most realistic to accept that these are attempts to negatively affect the EO’s public support, or the President’s approval. The question remains: Does the public listen?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Due to the constant nature of gridlock, the public can find satisfaction in a process of legislating that requires little debate and can instigate immediate changes in government functioning. Relying on EOs has become a tool that is used by Presidents to complete their policy agenda without the inclusion of the legislative branch. How presidents decide when and how to use EOs has always been an important part of the presidential literature. However, most previous work has failed to include public opinion in unilateral action calculus by the President. This has led to new research that includes this factor within their models (Christenson and Kriner 2017; Reeves and Rogowski 2015, 2016, 2018). These new works have not produced a clear answer to the effects of public opinion on unilateral action as a tool, or on specific policy of EOs. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Many different variables can play a role in whether a person agrees or disagrees with unilateral action. All recent works agree that partisanship, policy attitudes, and concerns over constitutionality of the action play a varying importance in individual support for EOs. Disagreement remains as to which factor should be taken most seriously when attempting to establish whether unilateral action usage is consequential to the public support of the President (Reeves and Rogowski 2016). 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; There is a paradigm that exists in Presidential behavior with regards to unilateral action. If a president suffers negative, long-term public opinion effect due to an EO, then we should expect that usage would become a more-rare phenomenon. However, if a President does not suffer consequences in approval, we should expect unwavering reliance on unilateral action as a tool of legislating. Neither of these cases accurately describes the current state of how the executive branch acts. This signals that there are conditions under which Presidents do and do not suffer consequences when it comes to their dependence on executive orders. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With the behavioral paradigm in presidential use of unilateral action, there also seems to be a public opinion conundrum. The Presidency is an impossible-to-please position in the US Government. Through public opinion polls it is shown that the public has distaste for strong executive power and its use (Mansfield 1989), yet also expects the president to get things done (Dickerson 2018). Everything from slow response to crises, bad weather, and even sports teams losing can have negative effects on the President’s public approval (Achen and Bartels 2002). The President must produce policy, but not by using executive power, and when it does not get completed through Congress, he or she will suffer the public approval punishment.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Among the most important problems that the President must address, are issues that their party brought attention to during the election. Ownership over issues allows parties and the President to create a brand or gain a reputation for being the party best at handling the issue (Petrocik 1996). Once in office, it is important for the President to act on issues that his or her party owns to both maintain their possession and to better their electoral outcomes. Issues that are owned are consistently the most salient and most tangible to the mass public. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When tallying all the expectations of the President, and what the public expects him to produce, the top of the President’s policy agenda will be the issues owned by the party. Through issue ownership the President provides a policy agenda to the public as to what they think is the most important problems facing the United States. Issues chosen by the parties regularly are issues that the party members see as important and want addressed. However, the issue ownership does not only cue co-partisans, but also provides the opposition with what to expect if the opponent wins. Both recognize that issues that the candidates focus on, will likely result in those leaders acting on the respective topics if they win the presidency. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In office, the elected President will choose to speak out about important issues, that are frequently the issues that their party owned during the election. By going public (Kernell 1997, Neustadt 1960), the president ultimately seeks to fulfill the policy promises made during the campaign. The issues that the President goes public with are initially meant to be handled in the legislative branch. However, by promoting the policy outcome most desirable to the President, the executive branch signals that they will act, if necessary, through unilateral action.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I present an initial theory that argues for inclusion of party identification within the model shown in Reeves and Rogowski (2018). It is hypothesized that when including party identification, the effects of the treatment are reduced or removed. Additionally, the data shows high correlation between support and party affiliation, which signals that the experiment did not achieve internal validity when attempting to remove the effects of party from their dependent variable.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the next section I provide a relevant literature review. Second, I offer a very brief initial theoretical section that then is test using the data currently available (Reeves and Rogowski 2018). Finally, I present a new theory for future consideration that highlights the strengths and weaknesses in the current state of the literature regarding public opinion and unilateral action.

##Relevant Literature

####Unilateral Action and the Public

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Modern presidents and the modern presidency have been greatly defined by the institutionalization and growth of executive power in the United States (Moe and Howell 1999; Howell 2003). With the growth of unilateral powers, two other branches of government cede power to the executive and have done so with little argument. The ability for the President of the United States to act unilaterally has become a common tactic for achieving desired political outcomes. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Adjusting to the new way of governing leaves some scholars fearful of the expansion of power. However, there are also scholars who seek to address why the use of unilateral action has been so limited, given the nature of ease with unilateral action in the government (Christenson and Kriner 2015). A key assumption made by all researchers on the matter of constraints to unilateral action: Presidents do not wield unlimited scope with their ability (Christenson and Kriner 2015, 2016, 2017a, 2017b; Krause and Cohen 1997; Reeves 2011; Reeves and Rogowski 2015, 2016, 2018; Rottinghaus and Warber 2015). 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Armed with an incredibly weak ability to formally punish the chief executive, Congress and the Courts are regularly sidelined in favor of unilateral action. Understanding that the president does not have boundless choice, but does have vast unchecked power at his disposal provides an interesting conundrum: What constrains presidential unilateral action?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Previous scholarship has oft narrowed on the institutional checks and balances of unilateral action use, such as divided government (Fine and Warber 2012), legislative branch constraints (Deering and Maltzman 1999; Mayer 1999, 2001), and the issue focused unilateral action (Mayer 2001; Marshall and Parcelle 2005). Until recently, the importance of public opinion as the main constraint to unilateral action has been sparse in the traditional literature. This paucity of public opinion’s importance has been built on in recent work addressing how it constrains presidential action.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Correspondingly, public opinion is recurrently thought to reflect peoples’ fear about tyranny and unchecked presidential power. Hence, presidents are constrained, or suffer consequences after, due to this fear. Tangible effects of support for unilateral powers has been at the center of the debate on how public opinion influences unilateral action (Christenson and Kriner 2017a, 2017b; Reeves and Rogowski 2016, 2018). Narrowly focusing on unilateral powers public support, while omitting contextual information, does not allow the experimenter the ability to apply the effects of support on power, to real-time usage.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Presidents who have wide popularity can extend their power to further lengths than those who do not have strong public support behind them (Thrower 2017; Jacobson 2003). Likewise, issues that have vast support for one side or the other allow the president more room to navigate using executive action because of the ability to claim majoritarian principals, and lack of response by Congress. The processes through which policy is made has most commonly been tested on the judicial (Gibson 1989) and legislative branch (Hibbing and Theiss-Morse 2002). 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Argued in Kriner (2015), presidents can and do use executive orders and action to benefit groups that are politically important to their electoral success. Through using their institutional (and oft unchecked) powers, presidents can better their own political outcomes. Use in this capacity is seen as a way to “rile the base” of support because the groups that benefit remember the deed, while the groups that disagreed end up forgetting about it or find something else to dwell on. Important to note is that presidents will only act on issues that their base of support already sees as important, which sheds light onto the condition of issue ownership by the President’s party.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Prior literature has sought to determine the nature of voter’s response to unilateral action (eg Christenson and Kriner, and Reeves and Rogowski) outside of the real political context, except for minor exploration in Reeves and Rogowski (2018). Formalizing the conditions under which Presidents suffer public approval consequences for unilateral action, and when they do not, it critical to the development of this brand of literature.




####Public Appeals and Issue Ownership

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Public appeals have long been a tool of presidential power (Neustadt 1960; Kernell 1997; Canes-Wrone 2001), where a leader presents their issue stance to the public in an effort to sway public opinion towards his or her desired policy outcome. Consideration of the public’s opinion on policy is important to the decision-making calculus of all who are elected, but the President has a special connection to their electorate because they are the only nationally elected representative of the people. Public appeals often are used in an attempt to overcome a stubborn Congress or set a policy agenda by drawing attention to an issue.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Through the use of issue ownership during campaigns, and going public once in office, the President can both set the agenda and prioritize items of the most importance to their administration. Copartisans are those most likely to support the President on issues and do support the desired policy outcome that are shared by the party and the president. These issues are salient to the masses, and often could be considered “polarizing” matters (Jacobson 2003).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Going public with critiques of the other branch’s handling of issues, or with qualms over the time being taken to complete a task can help guide voter’s to placing blame on the legislative branch. Additionally, it provides the President justification for acting unilaterally to achieve a popular policy. Many studies have signaled that political leaders habitually reach out to the public to try to shape public opinion on policies (eg Jacobs and Shapiro 2001).


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Strategically, going public can prime the public to the President’s opinion and grit towards an issue. Their stamina both allows voters to prepare for a change, provides transparency in what the President wants completed and in doing so leaves no confusion around the action he is willing to take. Many scholars have found that change often elicits a fear reaction from individuals (Barbalet 1995 for instance); however, when clearly stated and transparent about an action that will cause change, those effects can be decreased. Simply, people have shock-induced fear when changes occur if they had not expected it. By showing his figurative hand on a policy change sought after, the President lowers the shock-effect that comes from the change. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The theory behind issue ownership allows for voters to keep a tally that establishes party reputation for handling issues and issue areas. Petrocik (1996) presented the idea that parties, over time and with effort, can establish a reputation in the populace that distinguishes their ability to handle issues. An example of this would be the Democratic Party and healthcare or Republicans and terrorism. By establishing themselves as better at handling, voters then can decide, based on their most important issues, which brand they want to choose during the campaign.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To build this status as a candidate, the repeated priming and focus on the issue allows people to establish the connection (Petrocik et al 2004). Through their intentional ownership of an issue, the media then focuses on statements regarding the issue (Hayes 2008) being debated often unintentionally provided selective coverage of candidates on the issues they have specialized with. Focusing on issues that the party is assessed to best handle over the other, they attempt to increase their chances of electoral success in the election (Stubager 2018). Similar to how “going public” during a presidency often allows the executive to set the terms of negotiation and have the upper hand because of prestige, the party with the most important problem issue ownership goes public via repeated discussion of their strengths (in the eyes of the public).


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Overtime issue ownership can change, much as we saw Democrats become the party who is seen as handling civil rights change in the early 1980s. Change can occur when a party seen as best at handling an issue area is determined to have poor performance, or through party shifts and demographic shifts (Pope and Woon 2008a, 2008b). Other work has suggested that candidates ought to focus on their own issues unless they have both public opinion (Riker 1993) or a change in campaign/political environment that allows for an advantage seeking opportunity (Holbrook 1996). Additionally there is vast literature on economic voting and tally-counting over the past two decades (eg Wright 2012; Lewis-Beck et al 2004, 2007; Fiorina 1972).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In sum, by focusing on issues they are deemed at better handling during campaigns, candidates can increase their electoral success. After winning the presidency, use of “going public” can often allow the President to control the narrative on the issues, while also pushing Congress to take action. Without action, the president is able to justify unilateral action that does not shock people because it was unpredictable—they knew the importance due to going public. Combined, these two factors are important to understanding how the President conditionally uses unilateral action to better his electoral chances, as well as mitigate consequences.


##Initial Theory

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Christenson and Kriner (2017a, 2017b; henceforth CK) argue that partisanship and policy attitudes are the most important determinant of support for unilateral action. Reeves and Rogowski (henceforth RR) argue that abstract fear or distaste for unilateral action leads voters to all around, regardless of their policy attitude or partisanship, decrease support for a candidate. In agreement with CK, partisanship and policy attitudes when included in RR model will reduce, or negate the effects that voters punish candidates through their support due to abstract fear of unilateral action. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This is in part due to the effect of issue ownership, as well as that RR model does not truly exclude partisanship from the experiment. If partisanship was not apart of the individual’s decision-making structure in the experiment, a spurious relationship between party affiliation and the policy attitudes should be present. The causal mechanism is that partisan affiliation is primed when talking about issue areas, and because parties own issue areas, their voters respond more positively to the issues. With a high correlation between the policy attitude and party affiliation, we then cannot accurately represent the predictability of just party affiliation—a caveat that my future theoretical contribution will address. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An observable implication example would be that Democratic individuals would support a Democrat using unilateral action on an issue owned by Democrats, compared to an issue owned by Republicans. In the theoretical models provided, there is no measure included that directly can test for issue ownership. That being said, I believe that tangentially that measure can be captured by the correlation values between party identification and policy attitudes of the observations.

The original model provided in RR (2018):

>0. support for candidate ~ treatment * policy attitude

Proposed alternatives to this model:

>1. support for candidate ~ treatment * policy attitude + partisanship

>2. support for candidate ~ treatment + policy attitude + partisanship

To capture the treatment effects of whether the candidate uses unilateral action or works with Congress (as seen in Figure 1 of the Appendix), I also include a table representing the differences in support. However, my model includes the differences broken down by party identification, which allows for a clearer understanding as to what groups punish the candidate most when using unilateral action. For the treatment, the alternative models are used on both the treatment group for legislative action, and unilateral action.

###Hypotheses

With the inclusion of party identification into the model proposed by Reeves and Rogowski (2018), there are new ideas to be tested. The hypotheses center around what the inclusion of party will do with the data and have been mentioned in the previous section. 

>**H1:** *Party affiliation and policy attitudes are highly correlated and statistically significant.*

>**H2:** *when including party affiliation in the logit model, the difference between the unilateral action treatment group support and legislative treatment group support will decrease in size.*

>**H3:** *When including party affiliation in the logit model, the party who is most correlated with the policy attitude will have the smallest decrease in support for the candidate using unilateral action.* 

The first hypothesis is testing the internal validity of the original experiment. Second, I am testing whether or not there is a decrease in the treatment effects when including party identification. Finally, the original relationship found in the previous model, where the highest policy supporters are the voters who punished the candidate most, is examined once party is included.


##Preliminary Methods

###Hypothesis 1
























##Future Theoretical Additions

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Presented is a first (and rough) draft of a theory that accompanies the debate between Christenson and Kriner, and Reeves and Rogowski. This disagreement revolves around the consequences or advantages of unilateral action. The summarization of this strain of literature is provided in the Literature Review section. On one side, it is argued that the President is benefitted by copartisans support when using unilateral action (Christenson and Kriner). The bulk of public opinion downfall coming from those who disagree with the policy, or disagree with the President’s partisanship.  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Opposite this argument is that the president suffers public support consequences when using unilateral action to achieve policy outcomes, no matter the issue and no matter the issue attitude of the individuals. This is the outcome of negative public opinion regarding unilateral action, where partisans also have negative views of the leader (Reeves and Rogowski). Development of a middle-of-the-road approach is the ultimate goal of the new theory provided.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Addressing the question: How does public opinion influence unilateral action by the president? I present a conditional argument under which the president makes calculations. The main factors that are apart of the calculus to use unilateral action or not: 

>1.	Party reputation handling an issue
>2.	Copartisan support of the issue
>3.	Public support of the issue
>4.	Congressional action on the issue

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; These conditions are relevant among salient problems in the United States, where the public is aware of both the background of why the issue is important, as well as the policy options presented. When deciding whether to use unilateral action, the president will consider all four of the stated conditions. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For a president to not have long-term negative effects of unilateral action, the issue must be salient and the executive must **(1)**own the issue they are legislating on, **(2)**have majority of the party’s support on the issue, **(3)**have a majority of the electorate’s support on the issue, and **(4)**have had non-action from Congress on the issue. Wherefore the President meets this criterion, copartisans’ support will not decline in the short or long-term, and non-copartisans’ support will decline in the short-term but return to pre-unilateral action support in the long-term, all else being equal. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Copartisans have this reaction because the issue that the President acts on was supported by the party, owned by the party, action was taken, and overall the policy outcome is liked. There would be no long-term effects simply because public information is low for current events, and even lower for past-events (Pew 2011, 2012, 2013, 2014). Copartisans will remember the success of the policy change, not the mechanism by which it was achieved.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Non-copartisans have a short-term negative reaction to presidential use of unilateral action because of their party affiliation. Short-term effects exist because salience of how an issue was acted on is most important in the direct time frame after its occurrence. Long-term support will remain in-tact because a majority of the country supported the issue acted on, and the non-copartisan knew, due to both issue ownership and going public, that the issue was important to the President. The expectation is that the President will act on policy agenda items, and the policy agenda is well known to the American people, whether they agree or not.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; People care about the outcome of policy debates, not the mechanism through which the outcome is produced. When primed with unilateral action compared to cooperation, it is socially desirable for respondents to prefer cooperation. However, copartisans of the president already support the policy outcome of a prospective unilateral action, and therefore would not punish the president for succeeding in changing a policy. Additionally, the policy would have already been apart of the party’s policy agenda. If Congress does not take the appropriate action on the issue, the President is left with the option to either fail at producing a change or using unilateral action to achieve it. Copartisans prefer policy success over the means to which it was achieved—providing the main causal mechanism for the theory. 
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Non-copartisans will punish the President in the short-term no matter the specific policy attitude of the individual. There will not be long-term political support effects because non-copartisans understand that there are spoils of winning the Presidency. Because the president made clear the importance of an issue, and their desired policy outcome, the non-partisans expect action on the issue because they understand the costs of losing an election. Post-unilateral action, support among non-copartisans of the president will return to support levels pre-action, all else being equal. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Conversely, if the president issues a unilateral action on an issue without the conditions being met, the expectation is that there will be short-term consequences, and well as long-term consequences. The short-term dips in public support will come from both the copartisans and non-partisans. Long-term effects of unilateral action, particularly when less than a majority of the electorate does not support the issue, will be seen in the non-copartisans of the President. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A few key distinctions exist in this theory with regards to the previous work that has been done on the topic of unilateral action and public opinion. The first is the intentional omittance of policy attitude as a direct measure. Presidents act rationally, and through this rationality, they do not make decisions that are calculated to be harmful to their electoral success, or their party. With this assumption, it is fair to accept that unilateral action that the President takes, will not contrast with the public opinion of his copartisans. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Therefore, policy attitude and the realm of issues that a president would take unilateral action on are extremely correlated at the aggregate level. As shown later in the methods section, issues in the experiments done by Reeves and Rogowski, show clear partisan support even when a candidate in the experiment is not given a party label. Further evidence can be found in the Appendix (FIGURE XXX) where the models provided only marginally improve when including both policy attitude and party identification, as compared to including one or the other. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The second deviation with the current literature comes with the dissection of political time between short-term and long-term effects. Through the experiments, I believe that Reeves and Rogowski (2016, 2018) were simply capturing partisan, issue, primed, short-term effects due to the nature of their design. As opposed to Christenson and Kriner (2017) who found that, when using real-world examples of use of unilateral action given the context of non-action by Congress, there is no negative effects. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; While these methods do not test the same variables, they do point to different conclusions on whether people punish presidents for unilateral action. By combining these two different frameworks, a more suitable theory to the conditions under which public support declines. Both theories ignore important tangible cases that could provide insight to how public opinion functions in real political environments. Addressed in my theory is the importance of partisan identification and political information, as well as testing within the context of actual executive orders by Presidents that undertake salient issues.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Finally, as described in-depth in a proposed research design section, I intend to use real-world examples of salient executive orders and public opinion polls to draw conclusions and analyze the theory put forward in this paper. From briefly looking over a few of the most important issues of the last quarter-century, there is reason to believe that the theory will hold true at face-value, but no conclusions can be drawn without methodological proof and analysis. Hypotheses will be offered for testing in the research design portion found later in the paper.





































